/*
 * This source file was generated by the Gradle 'init' task
 */
package org.gjmorris;

public class App {
    public String getGreeting() {
        return "Hello World! jajaja";
    }

    public int sanity(){
        return 0;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
