/*
 * This source file was generated by the Gradle 'init' task
 */
package org.gjmorris;

import static org.junit.Assert.assertNotNull;
import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void sanityTest() {
        App app = new App();
        assert(app.sanity() == 1);
    }

}
